import 'package:intl/intl.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:flutter/services.dart' show rootBundle;

import '../../../core/pdf/pdf_footer.dart';
import '../../../core/pdf/pdf_header.dart';
import '../domain/tax_result.dart';

class IncomeTaxPdf {
  static Future<pw.Document> build({required TaxResult result}) async {
    final pdf = pw.Document();

    final regular = pw.Font.ttf(
      await rootBundle.load('assets/fonts/NotoSans-Regular.ttf'),
    );

    final bold = pw.Font.ttf(
      await rootBundle.load('assets/fonts/NotoSans-Bold.ttf'),
    );

    final formatter = NumberFormat.currency(
      locale: 'en_IN',
      symbol: '₹ ',
      decimalDigits: 2,
    );

    pdf.addPage(
      pw.MultiPage(
        theme: pw.ThemeData.withFont(base: regular, bold: bold),
        build: (_) => [
          pdfHeader(
            regular: regular,
            bold: bold,
            title: 'Income Tax Computation Report (FY 2026-27)',
          ),
          pw.Header(
            level: 1,
            child: pw.Text(
              'Executive Summary',
              style: pw.TextStyle(font: bold),
            ),
          ),

          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(font: bold),
            cellStyle: pw.TextStyle(font: regular),
            headers: ['Particular', 'Value'],
            data: [
              ['Annual Income', formatter.format(result.grossIncome)],
              ['Total Tax', formatter.format(result.totalTax)],
              ['Annual Take Home', formatter.format(result.takeHome)],
              ['Monthly Take Home', formatter.format(result.takeHome / 12)],
            ],
          ),

          pw.SizedBox(height: 20),
          pw.Header(
            level: 1,
            child: pw.Text('Taxpayer Details', style: pw.TextStyle(font: bold)),
          ),

          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(font: bold),
            cellStyle: pw.TextStyle(font: regular),
            headers: ['Field', 'Value'],
            data: const [
              ['Financial Year', 'FY 2026-27'],
              ['Assessment Year', 'AY 2027-28'],
              ['Tax Regime', 'New Regime'],
              ['Taxpayer Type', 'Salaried'],
              ['Currency', 'INR (₹)'],
            ],
          ),

          pw.SizedBox(height: 20),
          pw.Header(
            level: 1,
            child: pw.Text(
              'Report Information',
              style: pw.TextStyle(font: bold),
            ),
          ),

          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(font: bold),
            cellStyle: pw.TextStyle(font: regular),
            headers: ['Field', 'Value'],
            data: [
              [
                'Generated On',
                DateFormat('dd MMM yyyy, hh:mm a').format(DateTime.now()),
              ],
              ['Application', 'CoreNaksh Finance'],
              ['Version', '1.0'],
              ['Generated By', 'CoreNaksh Technologies'],
            ],
          ),

          pw.SizedBox(height: 20),

          pw.Header(
            level: 1,
            child: pw.Text(
              'Income Computation',
              style: pw.TextStyle(font: bold),
            ),
          ),

          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(font: bold),
            cellStyle: pw.TextStyle(font: regular),
            headers: ['Particular', 'Amount'],
            data: [
              ['Gross Income', formatter.format(result.grossIncome)],
              [
                'Standard Deduction',
                formatter.format(result.standardDeduction),
              ],
              ['Taxable Income', formatter.format(result.taxableIncome)],
            ],
          ),

          pw.SizedBox(height: 20),
          pw.Header(
            level: 1,
            child: pw.Text('Tax Computation', style: pw.TextStyle(font: bold)),
          ),

          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(font: bold),
            cellStyle: pw.TextStyle(font: regular),
            headers: ['Particular', 'Amount'],
            data: [
              ['Slab Tax', formatter.format(result.slabTax)],
              ['Rebate', formatter.format(result.rebate)],
              ['Surcharge', formatter.format(result.surcharge)],
              ['Health & Education Cess', formatter.format(result.cess)],
              ['Total Tax Liability', formatter.format(result.totalTax)],
            ],
          ),

          pw.SizedBox(height: 20),
          pw.Header(
            level: 1,
            child: pw.Text(
              'Take Home Summary',
              style: pw.TextStyle(font: bold),
            ),
          ),

          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(font: bold),
            cellStyle: pw.TextStyle(font: regular),
            headers: ['Particular', 'Amount'],
            data: [
              ['Annual Take Home', formatter.format(result.takeHome)],
              ['Monthly Tax', formatter.format(result.monthlyTax)],
              ['Monthly Take Home', formatter.format(result.takeHome / 12)],
              [
                'Effective Tax Rate',
                '${result.effectiveTaxRate.toStringAsFixed(2)}%',
              ],
            ],
          ),

          pw.SizedBox(height: 20),

          pw.Header(
            level: 1,
            child: pw.Text(
              'Slab-wise Tax Calculation',
              style: pw.TextStyle(font: bold),
            ),
          ),

          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(font: bold),

            cellStyle: pw.TextStyle(font: regular),
            headers: ['Income Slab', 'Rate', 'Taxable Income', 'Tax Payable'],
            data: result.breakdown
                .map(
                  (e) => [
                    e.slab,
                    '${(e.rate * 100).toStringAsFixed(0)}%',
                    formatter.format(e.taxableAmount),
                    formatter.format(e.tax),
                  ],
                )
                .toList(),
          ),

          pw.SizedBox(height: 20),

          pw.Header(
            level: 1,
            child: pw.Text('Tax Insights', style: pw.TextStyle(font: bold)),
          ),

          pw.Bullet(
            text:
                'Effective Tax Rate: ${result.effectiveTaxRate.toStringAsFixed(2)}%',
          ),

          pw.Bullet(
            text:
                'Monthly Tax Liability: ${formatter.format(result.monthlyTax)}',
          ),

          pw.Bullet(
            text: 'Annual Take Home: ${formatter.format(result.takeHome)}',
          ),

          pw.Bullet(
            text:
                'Monthly Take Home: ${formatter.format(result.takeHome / 12)}',
          ),

          pw.SizedBox(height: 20),
          pw.Header(
            level: 1,
            child: pw.Text('Notes', style: pw.TextStyle(font: bold)),
          ),

          pw.Bullet(
            text: 'Standard deduction has been applied where applicable.',
          ),

          pw.Bullet(text: 'Tax calculated using the selected financial year.'),

          pw.Bullet(text: 'Health & Education Cess calculated at 4%.'),

          pw.Bullet(text: 'Figures are rounded to two decimal places.'),

          pw.Bullet(text: 'This report is based solely on the values entered.'),

          pw.SizedBox(height: 20),
          pw.Header(
            level: 1,
            child: pw.Text('Disclaimer', style: pw.TextStyle(font: bold)),
          ),

          pw.Text(
            'This report is generated automatically by FinanceHub based on the information entered by the user. '
            'It is intended for informational purposes only and should not be considered professional tax advice. '
            'Please consult a Chartered Accountant before filing your Income Tax Return.',
          ),

          pdfFooter(regular: regular, bold: bold),
        ],
      ),
    );

    return pdf;
  }
}
