import 'package:pdf/widgets.dart' as pw;

pw.Widget pdfFooter({
  required pw.Font regular,
  required pw.Font bold,
}) {
  return pw.Column(
    children: [
      pw.Divider(),
      pw.SizedBox(height: 8),
      pw.Text(
        'Generated by FinanceHub',
        style: pw.TextStyle(font: bold),
      ),
      pw.Text(
        '© 2026 CoreNaksh Technologies',
        style: pw.TextStyle(font: regular),
      ),
    ],
  );
}